### ISSUE TITLE
npm test not working

### ISSUE THREAD

**Issue by supun19** [jedireza/frame#213]
node version v6.9.0
> frame@13.3.1 test /home/supun/WebstormProjects/consult/api-user
> lab -c -L

/home/supun/WebstormProjects/consult/api-user/node_modules/lab/bin/lab:50
const main = async () => {
                   ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm ERR! Test failed.  See above for more details.

**Comment by AYapejian** [comment]
This is due to your version of node, take a look [here](http://node.green/#ES2017-features-async-functions).  Recommend you upgrade to the latest LTS 8.9.x

**Comment by supun19** [comment]
yeah its works thank you
